import { cookies } from 'next/headers'

import { Providers } from './providers'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const cookieStr = typeof window === 'undefined' ? cookies().toString() : document.cookie
  return (
    <html lang="en">
      <body>
        <Providers cookies={cookieStr}>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
